### ISSUE TITLE
[BUG]: không thể đánh số cho thẻ subsection và subsubsection

### ISSUE THREAD

**Issue by chutrgiabao8302** [hoang-himself/hcmut-thesis#1]
### Description of the bug

Chào bạn, mình hiện đang tham khảo template Latex của bạn để viết khóa luận. Tuy nhiên, mình hiện đang gặp một số vấn đề sau:

- Thẻ subsection không đánh số được. (Ví dụ, thẻ section sẽ được đánh số 1.1 nhưng subsection lại không hiện lên là 1.1.1) và xảy ra tương tự với thẻ subsubsection
- Các thẻ subsection và subsubsection cũng không được hiện lên trong phần Mục lục (\tableofcontent).
![image](https://user-images.githubusercontent.com/84557929/226248404-fe9eccbd-57a9-46bf-a5d8-da968ec741ef.png)

Rất mong nhận được phản hồi sớm từ bạn,

Trân trọng,

### Steps To Reproduce

Mình chỉ thêm đúng 2 thẻ là subsection và subsubsection nhưng không ăn lệnh.

**Comment by hoang-himself** [comment]
Chào bạn. Để đánh số tới thẻ `subsubsection` và để ToC nhận thì bạn thêm code sau vào file .cls

```tex
\setsecnumdepth{subsubsection}
\setcounter{tocdepth}{3}
```

**Comment by chutrgiabao8302** [comment]
Cảm ơn bạn,

Gia Bảo

**Comment by chutrgiabao8302** [comment]
Cảm ơn bạn!!!

**Comment by chutrgiabao8302** [comment]
Anyway, format của bạn làm đẹp quá!!!
